#!/bin/bash
COMPILER=0
LINKER=0
STRIP=0
compilerOptions=""
verboseDefault="-DVERBOSE_LOGGING=0"
linkerOptions=""

function synopsis {
	echo "Compiles a program into an executable.
	
		
	Switches

-h				Shows Synopsis
-c --compiler	[OPTION]	Insert compiler options ("" for none)
-l --linker	[OPTION]	Insert linker options ("" for none)
-s --strip			Strip the executable of debugging information

	Usage Examples:

	build -h
		Show this synopsis.
		
	build [-c|--compiler OPTION] [-l|--linker OPTION]
		Build an executable in steps, passing compiler and linking options
	"
	exit
}

function compile {
	#need to check here for timestamp on helper
	if [ ! -e "helper.o" ];then
		gcc -c helper.c $compilerOptions
	fi

	if [ -e "helper.o" ];then 
		ar cr libhelper.a helper.o
		echo "lol"
	fi

	if $(grep -q "\-DVERBOSE_LOGGING" <<< "$compilerOptions");then
		gcc -c main.c   $compilerOptions
	else
		gcc -c main.c   $verboseDefault $compilerOptions
	fi
	
}

function link {
	echo "linking $linkingOptions"
	gcc -o main main.o libhelper.a -lm
}

function stripExec {
	echo "stripping"
	strip "main"
}

OPT=$(getopt -n "builder" -o "c:,l:,h,s" -l "compiler:,linker:,help,strip" -- "$@")


eval set -- "$OPT"


while [ "$1" != "--" ]; do
	case "$1" in 
	-c|--compiler)
		echo "compiler"
		COMPILER=1
		compilerOptions="$2"
		shift
		;;
	-l|--linker)
		echo "linker"
		LINKER=1
		linkerOptions="$2"
		shift
		;;
	-h|--help)
		synopsis
		;;
	-s|--strip)
		STRIP=1
		;;
	*)
		echo "Invalid Arguments"
		exit 1
		;;
	esac

	shift
done

if [ $COMPILER -eq 1 ] ;then
	compile
fi

if [ $LINKER -eq 1 ] ; then
	link
fi

if [ $STRIP -eq 1 ] ;then
	stripExec
fi
